---
platform: linux

inputs:
- name: terraform-state

params:
  CREDHUB_SERVER:
  CREDHUB_CA_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  # - ^CREDHUB_* variables
  # - Credhub connection details
  PREFIX:
  # - Prefix to credential in credhub

run:
  path: bash
  args:
  - "-c"
  - |
    credhub api
    credhub login

    pushd terraform-state/

    # Azure Storage Accounts
    credhub set -n "${PREFIX}"/azure-deploy-storage-account -t user \
        -z "$(terraform output deploy_backup_storage_account_name)" \
        -w "$(terraform output deploy_backup_storage_account_access_key)"
    # TODO: (@conzetti) put the actual variables in!
    credhub set -n "${PREFIX}"/azure-opsman-storage-account -t user \
        -z "$(terraform output opsman_backup_storage_account_name)" \
        -w "$(terraform output opsman_backup_storage_account_access_key)"
    credhub set -n "${PREFIX}"/azure-pas-storage-account -t user \
        -z "$(terraform output cf_storage_account_name)" \
        -w "$(terraform output cf_storage_account_access_key)"
    credhub set -n "${PREFIX}"/azure-state-storage-account -t user \
        -z "$(terraform output state_storage_account_name)" \
        -w "$(terraform output state_storage_account_access_key)"

    # Azure Base Credentials
    credhub set -n "${PREFIX}"/azure_client -t user \
        -z "$(terraform output client_id)" \
        -w "$(terraform output client_secret)"
    credhub set -n "${PREFIX}"/azure_resource_group -t value \
        -v "$(terraform output pcf_resource_group_name)"
    credhub set -n "${PREFIX}"/azure_subscription -t value \
        -v "$(terrraform output subscription_id)"
    credhub set -n "${PREFIX}"/azure_tenant_id -t value
        -v "$(terraform output tenant_id)"

    # Ops-Manager Credentials
    credhub set -n "${PREFIX}"/om_external_ip -t value \
        -v "$(terraform output ops_manager_public_ip)"
    credhub set -n "${PREFIX}"/om_internal_ip -t value \
        -v "$(terraform output ops_manager_private_ip)"
    credhub generate -n "${PREFIX}"/opsman_admin -t user \
        -z "admin"
    credhub set -n "${PREFIX}"/decryption_passphrase -t value \
        -v "$(credhub get -n "${PREFIX}"/opsman_admin -k password)"
    credhub set -n "${PREFIX}"/opsman_target -t value \
        -v "$(terraform output ops_manager_dns)"

    # FIXME (@austin) These aren't secret. Do we need these?
    # credhub set -n "${PREFIX}"/apps_domain -t value \
    #     -v "$(terraform output apps_domain)"
    # credhub set -n "${PREFIX}"/system_domain -t value \
    #     -v "$(terraform output sys_domain)"
    # credhub set -n "${PREFIX}"/router_lb_name -t value \
    #     -v "$(terraform output web_lb_name)"

    # credhub set -n "${PREFIX}"/pas_network_name -t value \
    #     -v "pas"
    # credhub set -n "${PREFIX}"/service_network_name -t value \
    #     -v "services"
    # credhub set -n "${PREFIX}"/azure_availability_sets -t value \
    #     -v "Availability Sets"
    # credhub set -n "${PREFIX}"/pcf_admin_email -t  value \
    #     -v "prometheus@logux.net"