#!/bin/bash

az storage blob download --container-name resources \
    --file platform-automation-image-3.0.1.tgz \
    --name platform-automation-image-3.0.1.tgz \
    --account-name 2vwjhaifhaf2lu887kic \
    --account-key TaTP5UDvjMFAhyf69syEQdqU75pq71+MH/D8GX7S5C/rks90ZuYIi6UnV5YyuvWdT9LrRq+jiUAGoHibuEV0eg==